server:
  port: 9004
spring:
  application:
    name: tensquare-base
  data:
    mongodb:
        host: 127.0.0.1
        port: 27017
        database: recruitdb
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_article
    username: root
    password: admin
  jpa:
    database: mysql
    show-sql: true

