server:
  port: 9012
spring:
  application:
    name: tensquare-web
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    tensquare-gathering:
      path: /gathering/**
      serviceId: tensquare-gathering
    tensquare_article:
      path: /article/**
      serviceId: tensquare_article
    tensquare_base:
      path: /base/**
      serviceId: tensquare_base
    tensquare_qa:
      path: /qa/**
      serviceId: tensquare_qa
    tensquare_recruit:
      path: /recruit/**
      serviceId: tensquare_recruit
    tensquare_search:
      path: /search/**
      serviceId: tensquare_search
    tensquare_spit:
      path: /spit/**
      serviceId: tensquare_spit
    tensquare_user:
      path: /user/**
      serviceId: tensquare_user
